### ISSUE TITLE
To display the end article of each prompt in the prompts table on the home page

### ISSUE THREAD

**Issue by tanishabelkar** [wikispeedruns/wikipedia-speedruns#160]
I think it would be helpful to have the end article of each prompt to be displayed so that would help users decide better.

**Comment by mliu59** [comment]
@dqian3 @bricehalder @maggarwal99 thoughts? I think this would make sense for public facing prompts that are not rated, but maybe not for rated prompts that users can only play once.

**Comment by maggarwal99** [comment]
Personally, I kinda like how it is right now. At the very least, rated prompts, as you mentioned, must not display the end article  before start. Actually this reminds me, we should change how/when we count a run to have started. Currently, we do this after the countdown page but we display the goal article on the countdown page. So players can easily start a rated prompt, see the goal article, and then leave before the countdown ends. And because their run won't be registered, they can play that rated prompt again. We can fix this by either a) removing the goal article from the countdown page and only displaying it in the time box once the run starts or b) by registering runs as soon as players hit to play a prompt as opposed to when the countdown ends. I think a) is better cuz countdown page serves as a buffer/staging area before the game starts where players should be able to exit the game without forfeiting and try again. Thoughts?

**Comment by mliu59** [comment]
Countdown was originally implemented as a staging area for players to look at the prompt and briefly decide on possible routes they would take before they get thrown into the articles themselves. I'm personally leaning towards keeping end article at least in the countdown

**Comment by maggarwal99** [comment]
Ok yea makes sense, so should we instead save runs as soon as players click "play"? The caveat being we would end up saving empty runs as well.

**Comment by dqian3** [comment]
> @dqian3 @bricehalder @maggarwal99 thoughts? I think this would make sense for public facing prompts that are not rated, but maybe not for rated prompts that users can only play once.

I agree with this definitely, and I'll probably implement that in #162 , since we're making so many changes to the the schema already. 

As for the countdown stuff, I think the time should start after the first article is loaded (see #155), but when the user loads a rated prompt (i.e. click "play") we should mark them as having an attempt. I think it already does in fact do that now, but that logic should be moved into the backend, and cleaned up a little

**Comment by bricehalder** [comment]
> Ok yea makes sense, so should we instead save runs as soon as players click "play"? The caveat being we might end up saving a lot of empty runs.

Yeah this is how we currently do it, and yeah about 3/4 runs are actually empty. Might be worth only doing it for rated runs.

**Comment by dqian3** [comment]
Oh didn't realize it was that many. Yeah I'm down to do it with only rated prompts. However, I think we need to make it more clear that when they click it starts their attempt. Also I was thinking about displaying more information about whether prompts have been played, e.g. by joining user runs when we query for prompts

**Comment by dqian3** [comment]
@tanishabelkar Seems like we never followed up on this, but it did end up getting solved in #162. If you look at the archive (https://wikispeedruns.com/archive) you can see the ended articles of each prompt.
