### ISSUE TITLE
Add option to hide end article in lobbies for participants

### ISSUE THREAD

**Issue by hay** [wikispeedruns/wikipedia-speedruns#455]
I'm planning on using the site for a competition during the Dutch Wikimedia conference (WikiCon 2022) ([site](https://www.wikimedia.nl/wikiconnl/)). For public competitions like this it would be really nice if there was a way to only reveal the end article the moment people hit 'play', comparable to how the daily prompt works. Otherwise people might have a bit of an advantage when they know the end article before hand.

UX-wise, this could be a checkbox right under the 'Add a prompt' form. Obviously, for the lobby organizer the end article would still be visible.

**Comment by dqian3** [comment]
Hi, this is super exciting! I can try and get on this as soon as possible.

The way I was thinking of implementing this would be to actually add a "competitive" option when creating the lobby. That way we can implement other changes such as preventing users from seeing results until they've played the prompt. However, if you want to control whether each prompt is visible to users I can do that as well.

By the way, how many people are you expecting to play at once? I don't think we've had a large number at once, and I want to make sure there aren't any issues due to load

**Comment by bricehalder** [comment]
Hey @hay, really glad to hear about this! In addition to the approximate number of concurrent participants, we were also wondering how the website performance is from the Netherlands? Our web server is based on the east coast USA I believe, so we might be able to tweak some things before the event.

If you're interested in having a communication channel with our team before/during the event, we can also set that up for you on our Discord (link at bottom of our site).

**Comment by hay** [comment]
Hey @dqian3 and @bricehalder really nice to hear that you're liking the idea of a competition! I'll check in later at the Discord. This is not going to have a lot of traffic, it's just going to be max 2-3 people at the same time. I didn't have any trouble with connectivity btw from the Netherlands, site runs speedy and fast.
