### ISSUE TITLE
Modify path JSON to support partial run information

### ISSUE THREAD

**Issue by mliu59** [wikispeedruns/wikipedia-speedruns#54]

**Comment by bricehalder** [comment]
If someone really wants to cheat, wouldn't they just disable this stuff client-side?

**Comment by bricehalder** [comment]
people can also just edit our JS code and easily win that way, maybe we can minify/obfuscate our code to account for that

**Comment by bricehalder** [comment]
I think it would be better to build out the path purely on the frontend, and then submit on page exit/prompt completion. Mostly it will massively reduce API calls to the server, since it would be an API call + database update on each click. This would be most egregious during a tournament is going, which is when we would want the server to be the most stable. One side benefit is that time calculation would be most precise on the frontend. Another benefit is that I will be designing it to be flexible to collect other information on the frontend about what things are clicked elsewhere on our site.

Especially as we scale I think this would really overwhelm the server so I'm going to implement it on the frontend for the reasons listed. I think a downside would be the susceptibility to JavaScript hacking, but if people are resorting to that, then they still have infinite other ways to cheat.
